import { Router } from 'express';
import { list, save, detail, remove } from '../controllers/user-books.js';
import { requireAuth } from '../middleware/auth.js';
import { validate } from '../middleware/validate.js';
import { shelfSchema, shelvesQuerySchema, personalBookSchema, removeShelfSchema } from '../validators/index.js';
export const userBooksRouter = Router();
userBooksRouter.get('/', requireAuth, validate(shelvesQuerySchema), list);
userBooksRouter.get('/:bookId', requireAuth, validate(personalBookSchema), detail);
userBooksRouter.delete('/:bookId', requireAuth, validate(removeShelfSchema), remove);
userBooksRouter.post('/', requireAuth, validate(shelfSchema), save);
